### ISSUE TITLE
Unable to build on windows

### ISSUE THREAD

**Issue by AmerM137** [Waqar144/lite-odin#1]
Hello!

I am glad I found this repo. I am learning Odin and was going to go through the same process.

I tried building this on Windows but I am getting a few issues, and I was wondering if you're able to help.

```
main.odin(39:10) Error: Cannot assign value 'dpi / 96.0' of type 'f32' to 'f64' in return statement
        return dpi / 96.0
               ^~~~~~~~~^

api_system.odin(292:8) Error: 'context' has not been defined within this scope, but is required for this procedure call
        m := windows.utf8_to_wstring(string(msg))
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^

api_system.odin(293:8) Error: 'context' has not been defined within this scope, but is required for this procedure call
        t := windows.utf8_to_wstring(string(title))
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^

api_system.odin(294:51) Error: Undeclared name: w
        ... indows.HWND(nil), m, w, windows.UINT(MB_YESNO | MB_ICONWARNING))
                                 ^

api_system.odin(294:67) Error: Undeclared name: MB_YESNO
        ... indows.HWND(nil), m, w, windows.UINT(MB_YESNO | MB_ICONWARNING))
                                                 ^~~~~~~^

api_system.odin(294:78) Error: Undeclared name: MB_ICONWARNING
        ... indows.HWND(nil), m, w, windows.UINT(MB_YESNO | MB_ICONWARNING))
                                                            ^~~~~~~~~~~~~^

api_system.odin(295:38) Error: Undeclared name: IDYES
        lua.pushboolean(L, cast(b32)(id == IDYES))
```

The odin compiler:
version dev-2024-12:597fba7

I am trying this using the latest commit f61a06b. I am not sure if you meant for this to be built on windows but I would appreciate any help.

**Comment by Waqar144** [comment]
Hi, thanks for trying. I never compiled it on windows so didn't know about the compilation errors. I have pushed some fixes, can you try again?

**Comment by AmerM137** [comment]
Got rid of most of the errors, I still see these:
The "^~~^" thing is messed up since I am hiding my user directory name, but both errors point to the "windows.utf8.to..." line.

```
api_system.odin(292:14) Error: 'context' has not been defined within this scope, but is required for this procedure call         message := windows.utf8_to_wstring(string(msg))
                   ^~~~~~~~~~~~~~~~~~~~~~~~^

api_system.odin(293:14) Error: 'context' has not been defined within this scope, but is required for this procedure call         caption := windows.utf8_to_wstring(string(title))
    ^~~~~~~~~~~~~~~~~~~~~~~~^
```

**Comment by Waqar144** [comment]
Should work now

**Comment by AmerM137** [comment]
yep, that built just fine! Now I just need to make sure I have to make sure lua54.dll and SDL2.dll are found. Thanks!

**Comment by AmerM137** [comment]
I copied the lua54.dll and SDL2.dll files from the odin vendor folder to the directory where lite-odin.exe is. I don't get a window though. All I get is "is ODIN DEBUG: false" on the cli then it terminates.

Am I supposed to do anything different than "odin build ." then copying the lua54.dll and SDL2.dll over?

**Comment by Waqar144** [comment]
No, it should just work. Maybe there is some windows specific issue.

Can you try building with:
```
odin build . -debug -sanitize:address
```
See if it prints something to the console. Unfortunately I don't have a windows PC atm so can't debug it myself

**Comment by AmerM137** [comment]
ok that worked. Not sure why the release build doesn't run. Anyway, I am happy for now. Thanks a lot for your help. I'll keep tinkering with this as I learn more Odin!

**Comment by Waqar144** [comment]
Also, i don't think you need to copy the dlls. 

If you find out the real issue, feel free to open a PR

**Comment by AmerM137** [comment]
Yeah, I guess the DLLs just need to be on path. If I figure out the issue I'll come back with an update for sure.
